Adding files from scib
theislab/scib-reproducibility pull request #4
Opened 2021-03-05 14:47 UTC by mumichae

Scripts added:

- [ ] `scripts/preprocessing.py`
- [ ] `scripts/run_normalize.sh`
- [ ] `scripts/sim_norm.py`

2021-03-05 18:05 UTC, LuckyMD approved these changes
ideally add the R/visualization stuff already now. But fine to do it in stages as well.

2021-03-06 05:04 UTC, mumichae commented
@martaint Is it safe to move all the `R/visualization` code here or are you still working on it?

2021-03-07 08:19 UTC, martaint commented
I think it's safe! I'm not working on it :)

On Sat, 6 Mar 2021, 06:05 Michaela Mueller <notifications@github.com> wrote:

> @martaint <https://github.com/martaint> Is it safe to move all the
> R/visualization code here or are you still working on it?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/theislab/scib-reproducibility/pull/4#issuecomment-791874602>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHR32OQTFPRXYMLCF3BZLB3TCGZX7ANCNFSM4YVK5JYQ>
> .
>

2021-03-08 09:01 UTC, lazappi commented on visualization/img/init
> +
Not sure where this blank file came from but can probably delete it.

2021-03-08 09:03 UTC, lazappi requested changes
Wow, that's a lot of notebooks! I assume somebody has already checked these are all still relevant?
* Do we need the `.ipynb_checkpoints` directories?

Should we move the data files in the `visualization/` directory to the top `data/` directory? At least those that are for the paper not just examples for the plotting functions (@martaint might be able to help with that).

2021-03-08 11:25 UTC, mumichae commented
> Wow, that's a lot of notebooks! I assume somebody has already checked these are all still relevant?

We removed notebooks some time back ([PR](https://github.com/theislab/scib/pull/94)), so I think things should be OK. @LuckyMD @danielStrobl Could you double-check if there are any notebooks we don't need anymore?

> 
>     * Do we need the `.ipynb_checkpoints` directories?
> 

Good point, didn't realise that I was adding those. They should be removed and ignored now.

> 
> Should we move the data files in the `visualization/` directory to the top `data/` directory? At least those that are for the paper not just examples for the plotting functions (@martaint might be able to help with that).

I agree, that would be better. We just need to update the R scripts accordingly.

2021-03-10 12:45 UTC, LuckyMD commented
Things I think might be removable:
1. The empty file @lazappi highlighted
2. Mouse atlas notebooks (@danielStrobl and @mumichae)
3. notebooks/Visualization_ATAC.ipynb from @kridsadakorn 
4. notebooks/silhouette_graph.ipynb, notebooks/trajectory_plots and notebooks/visualization.ipynb from @danielStrobl
5. visualization/atlas_heatmap.ipynb from @mumichae 

Would love to hear if you think these can be removed or if this is important for reproducibility. If important, then maybe we need a further folder.

2021-03-25 12:09 UTC, kridsadakorn reviewed
notebooks/Vitualisation_ATAC.ipynb can be deleted because the plots were replaced by Daniel's version.

PS. there is even a typo in the file name, poor me ...

2021-03-31 10:37 UTC, danielStrobl commented
One thing I noticed is that the notebooks/visualisation.ipynb in master is not the most recent one, it's actually in the `recompute_cluster_metrics` branch

2021-03-31 11:28 UTC, LuckyMD commented
Thanks for comments @danielStrobl. Could you say how you would name the folder (or in which existing folder) the notebooks to keep should be put? Just visualization?

2021-03-31 11:40 UTC, danielStrobl commented
Yes, sounds good

2021-04-01 07:59 UTC, lazappi commented
> One thing I noticed is that the notebooks/visualisation.ipynb in master is not the most recent one, it's actually in the `recompute_cluster_metrics` branch

@danielStrobl Can you open a separate PR for the latest version (or add it here)? Or open an issue I guess, just don't want to forget about this.

P.S. I think you have a pending invite to join this repo, I can resend if you need.

2021-04-01 08:53 UTC, danielStrobl commented
Ok, I'll open a PR for that. That would be great if you could resend the invite.

2021-04-06 02:57 UTC, mumichae commented
I agree that the heatmap and mouse atlas notebooks can be removed.

2021-04-06 03:14 UTC, mumichae commented
I removed the heatmap plotting script (duplicate) and moved the preprocessing scripts to the [Masterinternship_2019](https://github.com/theislab/Masterinternship_2019) repository.

2021-04-14 11:04 UTC, LuckyMD commented
also, new analysis notebook updates from scIB.

2021-04-15 15:25 UTC, lazappi commented
Summarising things that have come up in comments:

**Done**

- [x] Resend invite to @danielStrobl
- [x] Remove `.ipynb_checkpoints` directories
- [x] Remove mouse atlas notebooks 

**Todo**

- [ ] Remove empty `visualization/img/init` file
- [ ] Move the visualisation data files to the `data/` directory (this probably means other changes to scripts so maybe can be a later PR)
- [ ] Remove `notebooks/Vitualisation_ATAC.ipynb`
- [ ] Remove `visualization/atlas_heatmap.ipynb`
- [ ] Remove `notebooks/silhouette_graph.ipynb`
- [ ] Update `notebooks/visualisation.ipynb` to most recent version
- [ ] Other notebook updates from **scIB**?

Anything that's incorrect or I missed?

2021-04-15 15:32 UTC, lazappi commented
Also just noticed that each of the dataset notebook folders has an empty `README`. We should probably either add some info about the datasets or just delete them. @LuckyMD what do you think?

2021-04-15 18:02 UTC, LuckyMD commented
Could you copy over some text from the dataset description in the paper to the README?

2021-04-16 06:38 UTC, lazappi commented
> Could you copy over some text from the dataset description in the paper to the README?

That's definitely possible. Alternatively could describe what is in the notebooks (or both).

2021-04-16 14:25 UTC, LuckyMD commented
Or maybe better: everyone could write a small blurb (3-4 sentences of what is in the dataset). I think that could even be from the SI sections.

2021-04-22 10:13 UTC, lazappi commented
Did some of the minor things, see updated checklist https://github.com/theislab/scib-reproducibility/pull/4#issuecomment-820517623. Main things left to do are double checking notebooks are up to date (@danielStrobl can you help with that?) and deciding what to do with the READMEs.

2021-05-06 07:16 UTC, martaint commented
@lazappi I added a file in scib (https://github.com/theislab/scib/pull/234) which should also be added here in the respective notebook folder. Could you take care of that? Don't want to mess with this PR :) thanks a lot!

2021-06-14 12:08 UTC, lazappi approved these changes

2021-06-14 14:57 UTC, lazappi approved these changes

2021-06-14 14:58 UTC, merged